apiVersion: apps/v1
kind: Deployment
metadata:
  name: beeorganized-back-deployment
  labels:
    app: beeorganized-back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: beeorganized-back
  template:
    metadata:
      labels:
        app: beeorganized-back
    spec:
      containers:
      - name: beeorganized-container
        image: moohamedd/beeorganized:latest
        ports:
        - containerPort: 9999

---

apiVersion: v1
kind: Service
metadata:
  name: beeorganized-back-service
spec:
  type: LoadBalancer
  selector:
    app: beeorganized-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999
